---
- name: Install and Start Minikube on Slave server
  hosts: slave
  become: yes

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
      state: latest

  - name: Install Docker.io
    apt:
      name: docker.io
      state: latest

  - name: Install Kubectl
    shell: |
      sudo apt-get update && sudo apt-get install -y apt-transport-https
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubectl

  - name: Install Minikube
    shell: |
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      chmod +x minikube
      sudo mkdir -p /usr/local/bin/
      sudo install minikube /usr/local/bin/
      usermod -aG docker srbektimirov

#  - name: Command for Jenkins
#    shell: |
#      mkdir /home/srbektimirov/FinalProject
#      sudo useradd -m -s /bin/bash jenkins
#      mkdir /home/jenkins/.ssh
#      touch /home/jenkins/.ssh/authorized_keys
#      chown -R jenkins:jenkins /home/jenkins
#      sudo usermod -aG sudo jenkins

  - name: Reboot for start
    shell: |
      sudo reboot now
