---
- name: Install and Start Minikube on Slave server
  hosts: slave

  tasks:
  - name: Install Java
    apt:
      name: openjdk-11-jre
      state: present
    become: yes

  - name: Start Minikube
    shell: |
      minikube start
